- type: gameMapPool
  id: DefaultBlimpufMapPool
  maps:
  - BlimpufBagel
  - BlimpufCog
  - BlimpufCork
  - BlimpufFland
  - BlimpufHotel
  - BlimpufLagan
  - BlimpufLeth
  - BlimpufLobster
  - BlimpufManor
  - BlimpufMing
  - BlimpufOasis
  - BlimpufOrwell
  - BlimpufReach
  - BlimpufSaltern
  - BlimpufSepultum
  - BlimpufStarboard
  - BlimpufKiloton
  - BlimpufElkridge
  - BlimpufPrism
  - BlimpufSilica
  - BlimpufCluster
  - BlimpufBox
  - BlimpufPlasma
  - BlimpufPacked
  - BlimpufSpaceMall
  - BlimpufSerpentcrest
  - BlimpufBoxcars
  - BlimpufBarratry
  - BlimpufSushi
