using Content.Client.UserInterface.Controls;
using Content.Shared._Impstation.Service;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._Impstation.Service;

[GenerateTypedNameReferences]
public sealed partial class ServiceJobBoardMenu : FancyWindow
{
    //Funky begin - Fix deprecated function
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private IGameTiming _timing = default!;
    //Funky end - Fix deprecated function

    private ServiceJobEntry? _activeEntry;
    private TimeSpan? _endTime;

    public Action<string>? OnSelectButtonPressed;

    public ServiceJobBoardMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Update(ServiceJobBoardConsoleState state)
    {
        CurrentJobContainer.Children.Clear();
        _activeEntry = null;
        _endTime = state.EndTime;

        // available jobs are generated by the station
        foreach (var job in state.AvailableJobs)
        {
            var entry = new ServiceJobEntry(_prototypeManager.Index(job), _entityManager);
            entry.OnSelectButtonPressed += () => OnSelectButtonPressed?.Invoke(job);

            entry.Disabled = state.ActiveJob != null;
            entry.Selected = state.ActiveJob == job;

            //Funky/Blimpuf begin - Added a countdown to the job board UI
            if (entry.Selected && state.EndTime != null)
            {
                _activeEntry = entry;
                UpdateTimer();
            }

            CurrentJobContainer.AddChild(entry);
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        UpdateTimer();
    }

    private void UpdateTimer()
    {
        if (_activeEntry == null || _endTime == null)
            return;

        var remaining = _endTime.Value - _timing.CurTime;
        if (remaining < TimeSpan.Zero)
            remaining = TimeSpan.Zero;

        _activeEntry.Timer = remaining.ToString(@"hh\:mm\:ss");
    }
}
//Funky end - Added a countdown to the job board UI
