- type: entity
  name: enforcer stun baton
  parent: [ BaseStunbaton, BaseRepresentativesContraband, BaseContrabandTier2 ]
  id: EnforcerStunbaton
  components:
  - type: Sprite
    sprite: _Blimpuf/Objects/Weapons/Melee/ccestunbaton.rsi
    layers:
    - state: stunbaton_off
      map: [ "enum.ToggleableVisuals.Layer" ]
