- type: job
  id: CentralCommandOperator
  name: job-name-centcommoperator
  description: job-description-centcomoperator
  playTimeTracker: JobCentralCommandOperator
  setPreference: false
  startingGear: CentcomOperatorGear
  icon: JobIconCentralCommandOperator
  rules: job-rules-corporate-aligned
  supervisors: job-supervisors-hos
  bypassEorPacification: true
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: CentcomOperatorGear
  equipment:
    jumpsuit: ClothingAltUniformJumpsuitCentcomOfficial
    back: ClothingBackpackSatchelCentcomm
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesCentComm
    gloves: ClothingHandsGlovesColorBlack
    id: CentCommOperatorPDA
    ears: ClothingHeadsetAltCentCom
    pocket1: WeaponPistolN1984
    pocket2: BoxFolderCentComClipboardEmpty
  storage:
    back:
    - RubberStampCentcom
    - MindShieldImplanter

# Central Department of Guest Services CDGS
- type: startingGear
  id: CentralGuestServicesDepartmentGear
  equipment:
    jumpsuit: ClothingUniformJumpskirtCentcommDomesticFormalWear
    back: ClothingBackpackSatchelCentcomm
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesCentComm
    gloves: ClothingHandsGlovesColorBlack
    id: CentcomPDA
    ears: ClothingHeadsetAltCentCom
    pocket1: WeaponPistolN1984
    pocket2: BoxFolderCentComClipboardEmpty
  storage:
    back:
    - RubberStampCDGS
    - MindShieldImplanter

# Central Department of Administrative Action CDAA
- type: startingGear
  id: CentralAdministrativeDepartmentGear
  equipment:
    jumpsuit: ClothingUniformJumpskirtCentcommAdminFormalWear
    back: ClothingBackpackSatchelCentcomm
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesCentComm
    gloves: ClothingHandsGlovesHop
    id: CentcomPDA
    ears: ClothingHeadsetAltCentCom
    belt: BoxFolderHoPClipboard
    pocket1: WeaponPistolN1984
    pocket2: BoxFolderCentComClipboardEmpty
  storage:
    back:
    - RubberStampCDAA
    - MindShieldImplanter

# Central Department of Logistics CDL
- type: startingGear
  id: CentralLogisticsDepartmentGear
  equipment:
    jumpsuit: ClothingUniformJumpskirtCentcommCargoFormalWear
    back: ClothingBackpackSatchelCentcomm
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesCentComm
    gloves: ClothingHandsGlovesColorBlack
    id: CentcomPDA
    ears: ClothingHeadsetAltCentCom
    pocket1: WeaponPistolN1984
    pocket2: BoxFolderCentComClipboardEmpty
  storage:
    back:
    - RubberStampCDL
    - MindShieldImplanter

# Central Department of Engineering CDE
- type: startingGear
  id: CentralEngineeringDepartmentGear
  equipment:
    jumpsuit: ClothingUniformJumpskirtEngiCentcommFormalWear
    back: ClothingBackpackSatchelCentcomm
    shoes: ClothingShoesBootsMagAdv
    head: ClothingHeadHatBeretEngineering
    eyes: ClothingEyesGlassesCentComm
    gloves: ClothingHandsGlovesColorYellow
    id: CentcomPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltChiefEngineerFilled
    pocket1: WeaponPistolN1984
    pocket2: BoxFolderCentComClipboardEmpty
  storage:
    back:
    - RubberStampCDE
    - MindShieldImplanter

# Central Department of Health and Medicine CDHM
- type: startingGear
  id: CentralMedicineDepartmentGear
  equipment:
    jumpsuit: ClothingUniformJumpskirtCentcommMedFormalWear
    back: ClothingBackpackSatchelCentcomm
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesCentComm
    gloves: ClothingHandsGlovesNitrile
    id: CentcomPDA
    ears: ClothingHeadsetAltCentCom
    pocket1: WeaponPistolN1984
    pocket2: BoxFolderCentComClipboardEmpty
  storage:
    back:
    - RubberStampCDHM
    - MindShieldImplanter

# Central Department of Research CRD
- type: startingGear
  id: CentralResearchDepartmentGear
  equipment:
    jumpsuit: ClothingUniformJumpskirtCentcommResearchFormalWear
    back: ClothingBackpackSatchelCentcomm
    shoes: ClothingShoesBootsLaceup
    head: ClothingHeadHatCentcomcap
    eyes: ClothingEyesGlassesCentComm
    gloves: ClothingHandsGlovesColorPurple
    id: CentcomPDA
    ears: ClothingHeadsetAltCentCom
    pocket1: WeaponPistolN1984
    pocket2: BoxFolderCentComClipboardEmpty
  storage:
    back:
    - RubberStampCDR
    - MindShieldImplanter

# Central Department of Security and Welfare CDSW
- type: startingGear
  id: CentralSecurityDepartmentGear
  equipment:
    jumpsuit: ClothingUniformJumpskirtCentcommSecurityFormalWear
    back: ClothingBackpackSatchelCentcomm
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesCentComm
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorCentcommCarapace
    id: CentcomPDA
    ears: ClothingHeadsetAltCentCom
    belt: CentcommVibrobladeSheathFilled
    pocket1: WeaponPistolN1984
    pocket2: BoxFolderCentComClipboardEmpty
  storage:
    back:
    - RubberStampCDSW
    - MindShieldImplanter



