- type: department
  id: Representatives
  name: department-Representatives
  description: department-Representatives-description
  color: "#2C6E2E"
  roles:
    - BlueShield
    - Magistrate
    - NanoTrasenRepresentative
    - IAA
    - Decimus
    - NanoTrasenSpecialForces
    - NanotrasenCareerTrainer
  primary: false
  weight: 50
